name: Stackspot workflow dispatch
run-name: ${{ inputs.correlation_id }}
on: 
  workflow_dispatch:
    inputs:
      correlation_id:
        description: Correlation id
        required: true
      workflow_name:
        description: Workflow path
        required: true
      secrets:
        description: Secrets info (json)
        required: true
      api_inputs:
        description: Workflow inputs (json)
        required: true
jobs:
  run:
    name: Run workflow ${{ github.event.inputs.workflow_name }}
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LANGUAGE: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: utf-8
      HTTP_ENABLE_DEBUG: false
    steps:
      - name: Node.js with node_modules cache
        uses: magnetikonline/action-node-modules-cache@0b4ad87d575ee27fac4196064d478a9de926cfe3
        with:
          node-version: '18'
          package-lock-path: package-lock.json

      - name: Install npm
        run: npm install
   
      - name: Running ${{ inputs.workflow_name }}
        run: |
          secret_stk_login=$(echo '${{ inputs.secrets }}' | jq -cr '.cli_token')
          execution_id=$(echo '${{ inputs.api_inputs }}' | jq -cr '.execution_id')

          curl -o script.sh https://workflow-api.v1.stackspot.com/workflows/$execution_id --header "Authorization: Bearer $secret_stk_login"
          chmod +x script.sh

          echo "------------------------------------------------------------------------------------------"
          echo "---------------------------------------- Starting ----------------------------------------"
          echo "------------------------------------------------------------------------------------------"

          bash script.sh

          echo "------------------------------------------------------------------------------------------"
          echo "----------------------------------------  Ending  ----------------------------------------"
          echo "------------------------------------------------------------------------------------------"

